import "./globals.css";
import { Inter } from "next/font/google";
import app from "@/github";
import ClientLayout from "@/app/components/ClientLayout";
import { Session, getServerSession } from "next-auth";
import { AuthOptions, DEBUG } from "@/auth/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  if (DEBUG) {
    console.log("SS Render", !!app);
  }

  const session = await getServerSession(AuthOptions);
  if (DEBUG) {
    console.log("session", session);
  }
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientLayout session={session as Session}>{children}</ClientLayout>
      </body>
    </html>
  );
}
